name: Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

# Only run one workflow at a time per branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    name: Build and push images
    timeout-minutes: 90
    strategy:
      matrix:
        include:
          - image-name: gpac
            platforms: linux/amd64,linux/arm64
          - image-name: anacrolix-confluence
            platforms: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Prepare image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
          labels: |
            org.opencontainers.image.title="${{ matrix.image-name }}"
            org.opencontainers.image.description=""
            org.opencontainers.image.authors="alexandre@jouandin.eu"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platforms }}
          context: "{{defaultContext}}:${{ matrix.image-name }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
