name: Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  third-party:
    strategy:
      matrix:
        include:
          - directory: anacrolix-confluence
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.directory }}:latest
          context: "{{defaultContext}}:3rd-party/${{ matrix.directory }}"
